#!/usr/bin/env bash
# Script that configures the hosts file to change localhost and facebook.com IPs

# Sauvegarde du fichier hosts original
sudo cp /etc/hosts /etc/hosts.bak

# Création d'un fichier temporaire
sudo sed '/^127.0.0.1/d' /etc/hosts > /tmp/hosts
sudo sed '/^127.0.0.2/d' /tmp/hosts > /tmp/hosts2
sudo sed '/facebook.com/d' /tmp/hosts2 > /tmp/hosts3

# Ajout des nouvelles entrées
echo "127.0.0.2 localhost" | sudo tee -a /tmp/hosts3
echo "8.8.8.8 facebook.com" | sudo tee -a /tmp/hosts3

# Remplacement du fichier hosts
sudo mv /tmp/hosts3 /etc/hosts 